version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\SerialPortLib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - SerialPortLib.Tests/bin/Debug/SerialPortLib.Tests.dll
after_test:
  - ps: .\SerialPortLib\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: SerialPortLib nupkg
    type: NuGetPackage
deploy:
  - provider: GitHub
    auth_token:
      secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: oy2fxpnf5ahh6gs6xvkaqi5j3amzs4cetjedkjx5kzqqhm
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

